### ISSUE TITLE
Laravel 5.5 compatible?

### ISSUE THREAD

**Issue by leandroruel** [larapacks/authorization#16]
can i use this class with laravel 5.5, since some things changed in the source code? also, i can use it with my api to block routes?

**Comment by vFire** [comment]
same question...

**Comment by stevebauman** [comment]
Hi, yes it's compatible, I'm using this right now in production on 5.5.

I'm going to add the service provider to the 'extra' section for automatic service provider registration in Laravel 5.5

You can also use it on your API, there's no limitations there.
