### ISSUE TITLE
class permission not found

### ISSUE THREAD

**Issue by leandroruel** [larapacks/authorization#17]
installed and set the path to my permission, role and user model at config/authorization, however, returns me this error: Class permission does not exist.

but it exists and i'm using it.

**Comment by stevebauman** [comment]
Hi @leandroruel, are you caching your configuration at all?

You could try running the command `php artisan config:clear` to make sure.

Could you also post your authorization config file as well as your Permission model?

**Comment by leandroruel** [comment]
i figure out the problem, i not set the class on Kernel. my bad.
 but now i have another issue, i configured the middleware at my route,` ['middleware'=> ['permission:users.index']]` and even with the permission at table he returns unauthorized.

**Comment by stevebauman** [comment]
No problem!

You will need to add the `permission:` prefix to your middleware string:

```php
Route::group(['middleware' => ['permission:users.index']], function (() {
 
    // My routes.

});
```

Or if it's a role use `role:`:

```php
Route::group(['middleware' => ['role:users.index']], function (() {
 
    // My routes.

});
```

**Comment by stevebauman** [comment]
Also, make sure the user has the permission **or** the role that contains this permission.

**Comment by leandroruel** [comment]
not sure if it works in a resource route, but this is what i made:
```php
Route::resource('users', \App\Users\Controllers\UsersController::class,
		[
			'middleware' => ['permission:users.index, users.create']
		]
);
```

**Comment by stevebauman** [comment]
Can you remove the space in-between the `users.index, users.create` string?

Also, the user accessing this route will need **both** `users.index` and `users.create` permissions to access the route.

Do they have these permissions attached to their role / user model?

**Comment by leandroruel** [comment]
i'm recreating all permissions again to attach to my user, but one question, what means the "closure" column at permissions table? the values i'm storing at that table is name="Users View", label="users.view", closure=??

well now i understand after study the repository, but one thing i'm curious, at middleware if i put: permission:users.index it not work, returns "unauthorized", but if i put users.view it works, this is a bug?

**Comment by BBEDERRAR** [comment]
add this middlware in the kernel.php

 protected $routeMiddleware = [
        'auth' => \Illuminate\Auth\Middleware\Authenticate::class,
        'auth.basic' => \Illuminate\Auth\Middleware\AuthenticateWithBasicAuth::class,
        'bindings' => \Illuminate\Routing\Middleware\SubstituteBindings::class,
        'can' => \Illuminate\Auth\Middleware\Authorize::class,
        'guest' => \App\Http\Middleware\RedirectIfAuthenticated::class,
        'throttle' => \Illuminate\Routing\Middleware\ThrottleRequests::class,
        'role' => \Spatie\Permission\Middlewares\RoleMiddleware::class,
        'permission' => \Spatie\Permission\Middlewares\PermissionMiddleware::class,
    ];

**Comment by stevebauman** [comment]
Hi @leandroruel,

> i'm recreating all permissions again to attach to my user, but one question, what means the "closure" column at permissions table?

You can read of permission closures here:

https://github.com/larapacks/authorization#closure-permissions

> well now i understand after study the repository, but one thing i'm curious, at middleware if i put: permission:users.index it not work, returns "unauthorized", but if i put users.view it works, this is a bug?

This sounds like the user doesn't have the `users.index` permission? Do they have that permission attached?

Also @BBEDERRAR, your suggestion is for the wrong repository.

I'll close this issue since the original problem has been resolved, but if you encounter any other problems please let me know, thanks!
