### ISSUE TITLE
QueryException: Base table or view not found: 'dockerApp.role_role' doesn't exist

### ISSUE THREAD

**Issue by sifex** [larapacks/authorization#18]
Hey,

Getting this error, might investigate tonight, but for now I might as well post here because it looks like a package error.

```
Illuminate\Database\QueryException with message 'SQLSTATE[42S02]: Base table or view not found: 1146 Table 'dockerApp.role_role' doesn't exist (SQL: insert into `role_role` (`role_id`) values (2))'
```

with Role and Permissions looking like this respectively

```
=> Sudo\Role {#898
     name: "administrator",
     label: "Administrator",
     updated_at: "2018-03-19 20:59:20",
     created_at: "2018-03-19 20:59:20",
     id: 1,
   }
```

```
=> Sudo\Permission {#892
     name: "users.create",
     label: "Create Users",
     updated_at: "2018-03-19 20:58:51",
     created_at: "2018-03-19 20:58:51",
     id: 1,
   }
```

One of my guesses is that you might be defaulting to the App namespace somewhere that's hardcoded, but I've changed it to `Sudo`

**Comment by stevebauman** [comment]
Hi @sifex,

Can you post your usage?

My guess is you may have not published the configuration file and configured your models inside.

**Comment by sifex** [comment]
@stevebauman best reply time ever. 

Yep, that's exactly it, didn't check the config file and that had links to the `App` namespace. I'll see if I can add a PR to change it to the Autoload PSR-4 (and if not default to `App/`)

```json
"psr-4": {
    "Sudo\\": "app/"
}
```

**Comment by stevebauman** [comment]
Awesome @sifex, that'd be great! Thanks for the quick response :)

**Comment by sifex** [comment]
Just an update on this. Figured it's actually more clean to use the config file to specify the Role and Permissions Model, and anyone who changes the default namespace is (should be) smart enough to look in the config file.
