### ISSUE TITLE
How can i to associate the guards to Role?

### ISSUE THREAD

**Issue by kruiz122893** [larapacks/authorization#20]
Hi @stevebauman 

Could you please explain me how to associate the rolle "administrator" to user from Active Directory?

I need to add users to active directory group?
I need to import all users a local db (active directories)? https://ldaprecord.com/docs/laravel/auth/importing/

Just i need to hide this button for users than doesn't have permissions

![image](https://user-images.githubusercontent.com/26779953/82832860-95d1af80-9e79-11ea-8118-b083cac23523.png)

Regards

**Comment by stevebauman** [comment]
Hi @kruiz122893!

I'll walk you through how I have done this in my applications.

In the example I show you below, I will use a database seeder, but you can also use a migration instead if you prefer.

Create a database seeder by running the below artisan command:

```bash
php artisan make:seeder RoleSeeder
```

A new seeder will appear in your `database/seeds` folder (`database/seeds/RoleSeeder.php`).

This seeder will be responsible for creating our Laravel applications roles in our database.

Modify it to the below code:

```php
<?php

use Illuminate\Database\Seeder;
use Larapacks\Authorization\Role;

class RoleSeeder extends Seeder
{
    /**
     * The application roles.
     *
     * @var array
     */
    protected $roles = [
        [
             'name' => 'administrator',
             'label' => 'Administrator',
        ],
    ];

    /**
     * Run the database seeds.
     *
     * @return void
     */
    public function run()
    {
        foreach ($this->roles as $role) {
            $role = Role::firstOrCreate([
                'name' => $role['name'],
                'label' => $role['label'],
            ]);
        }
    }
}
```

See the [Laravel documentation](https://laravel.com/docs/7.x/seeding) for more about database seeding.

Then, edit the `database/seeds/DatabaseSeeder.php` file to include your new `RoleSeeder`:

```php
<?php

use Illuminate\Database\Seeder;

class DatabaseSeeder extends Seeder
{
    /**
     * Seed the application's database.
     *
     * @return void
     */
    public function run()
    {
        $this->call(RoleSeeder::class);
    }
}
```

Afterwards, run your database seeder:

```bash
php artisan db:seed
```

This will insert your application roles into your database.

Now we will perform the mapping of the LDAP role.

We will do this by listening for the LdapRecord-Laravel `Authenticated` event:

```
LdapRecord\Laravel\Events\Authenticated
```

Create a listener named `AssignRole` by running the below command:

```php
php artisan make:listener AssignRole
```

In the created listener, we will check if the LDAP user is a member of a group, and then attach the `Administrator` role to their account:

```php
<?php

namespace App\Listeners;

use Larapacks\Authorization\Role;
use LdapRecord\Laravel\Events\Authenticated;
use LdapRecord\Models\ActiveDirectory\Group;

class AssignRole
{
    /**
     * Handle the authenticated event.
     *
     * @param Authenticated $event
     *
     * @return void
     */
    public function handle(Authenticated $event)
    {
        if (! $group = Group::findByAnr('Web Administrator')) {
            return;
        }

        if (! $role = Role::where('name', '=', 'administrator')->first()) {
            return;
        }

        // We will make sure the users database model is saved
        // before we start performing role operations.
        $event->model->save();

        if (! $event->user->groups()->recursive()->exists($group)) {
            // The user is not a member of our LDAP administrator
            // group. We will detach roles incase they have been
            // removed from the LDAP group.

            $event->model->roles()->detach();
            
            return;
        }
       
        // The user is a member of LDAP administrator group. Add the role to their account.
        $event->model->roles()->sync($role);
    }
}
```

Then, in our views, we can use:

```php
@if(auth()->user()->hasRole('administrator'))
    Only an administrator can see this message.
@endif
```

Let me know if you require any further guidance 👍

**Comment by kruiz122893** [comment]
Does this listener ask if my user belongs to the group? (It would be great)

or my users must exist in my database?

![image](https://user-images.githubusercontent.com/26779953/82837168-86586380-9e85-11ea-85bd-06262855f750.png)


![image](https://user-images.githubusercontent.com/26779953/82837193-940de900-9e85-11ea-91cb-6239d5ca43f3.png)

**Comment by stevebauman** [comment]
This error indicates to me that you're not using database synchronization. Are you using [plain synchronization](https://ldaprecord.com/docs/laravel/auth/configuration/#plain)?

**Comment by kruiz122893** [comment]
![image](https://user-images.githubusercontent.com/26779953/82839537-eb638780-9e8c-11ea-8b26-474d147712b5.png)


No, because i use Active directories to do login
Never my app ask the DB for use these users


We need it?

**Comment by kruiz122893** [comment]
Hi @stevebauman  



**If you have another idea I would appreciate it**

**Comment by stevebauman** [comment]
Sorry @kruiz122893, my mistake. I thought you were using database synchronization.

If you are not using database synchronization and importing your users, you do not need this library or any other one, as it requires the ability to attach roles to specific user ID's inside of your Laravel applications database.

> We need it?

That's totally up to you. If you prefer to check for group existence on the authenticated LDAP user instead of synchronizing them into your database, you can absolutely to that.

If you are going in this direction, I would create a PHP trait that you apply to your `App\Ldap\ad1\User::class` and `App\Ldap\ad2\User::class` to make checking for group memberships easier:

**The Trait:**
```php
namespace App\Ldap;

use LdapRecord\Models\ActiveDirectory\Group;

class HasGroups
{
    public function hasGroup($groupName)
    {
        return $this->groups()->exists(
            Group::on($this->connection)->findByAnr($groupName)
        );
    }
}
```

**Your LdapRecord Models**:

Then add the trait to each of your LdapRecord models like so:

```php
use App\Ldap\ad1;

use App\Ldap\HasGroups;

User extends Model
{
    use HasGroups;
}
```

```php
use App\Ldap\ad2;

use App\Ldap\HasGroups;

User extends Model
{
    use HasGroups;
}
```

**Your Blade Views**

You can then check for group membership like so:

```blade
@if(auth()->user()->hasGroup('administrators'))
    <!-- This user is an administrator! -->
@endif
```

Is this what you're looking for?

**Comment by kruiz122893** [comment]
Hey man you are really really awesome
Thanks dude!!!



Just for documentation i will put the summary 👍 



![image](https://user-images.githubusercontent.com/26779953/82930492-b9146180-9f42-11ea-95c7-df90adcd9faa.png)

![image](https://user-images.githubusercontent.com/26779953/82930518-c0d40600-9f42-11ea-9802-e271856b8b07.png)

![image](https://user-images.githubusercontent.com/26779953/82930526-c5002380-9f42-11ea-96e9-d055e8411868.png)

**Comment by kruiz122893** [comment]
Now i don't have errors,
but my user belong to administrators

![image](https://user-images.githubusercontent.com/26779953/82931285-edd4e880-9f43-11ea-9eb4-b0e03627f990.png)



and now i can not view the button
![image](https://user-images.githubusercontent.com/26779953/82932131-2d500480-9f45-11ea-9631-4d39214a2e59.png)




It doesn't matter which user I use i can't view the buttons

**Comment by stevebauman** [comment]
Ok, can you try making this change to the trait?

```php
public function hasGroup($groupName)
{
    return $this->groups()->recursive()->exists(
        Group::on($this->connection)->findByAnr($groupName)
    );
}
```

> I added the `recursive()` call to the above query.

Also, run `composer update` to ensure you're using the latest LdapRecord version as well 👍 

Let me know if it works!

**Comment by kruiz122893** [comment]
Now i can view the buttons without matter the users group



Model ad1

![image](https://user-images.githubusercontent.com/26779953/82941203-3778ff80-9f53-11ea-8c1f-2b2ba34a88b8.png)


Model ad2

![image](https://user-images.githubusercontent.com/26779953/82941228-4069d100-9f53-11ea-9567-d5563dc3ada2.png)



APP\Traits\HasGroups.php


![image](https://user-images.githubusercontent.com/26779953/82941333-6becbb80-9f53-11ea-8b62-22ea4f329255.png)

**Comment by stevebauman** [comment]
So the users you are logged in with are not members of the `Administrators` group?

The `recursive()` call loads groups of groups. Is the `Administrators` group a member of another group in your domain?

**Comment by stevebauman** [comment]
Try removing the `recursive()` call and try again.

What we're looking to do here is retrieve the currently authenticated users Active Directory groups and then check if your `Administrator` group is contained inside.

You don't have any other groups in your domains named `Administrator` right? I ask because we are using a `findByAnr()` call, which will ask Active Directory for the first matching group by the given name.

This means if you have multiple groups in your domain named `Administrator`, it may be returning a different one.

**Comment by kruiz122893** [comment]
User cruiz@amavis.com:

![image](https://user-images.githubusercontent.com/26779953/82941703-1369ee00-9f54-11ea-9966-7c1265f641ad.png)

![image](https://user-images.githubusercontent.com/26779953/82941776-31375300-9f54-11ea-9537-4f5ef05581ab.png)

User mey@amavis.com

![image](https://user-images.githubusercontent.com/26779953/82941893-617ef180-9f54-11ea-9a19-604b5b18efa8.png)



![image](https://user-images.githubusercontent.com/26779953/82941928-73f92b00-9f54-11ea-89ca-8c7aa9390399.png)

**Comment by stevebauman** [comment]
Strange... Can you login to mey@amavis.com and then dump the users group names inside of your blade view and post the result:

```blade
{{ dd(auth()->user()->groups()->map->getFirstAttribute('cn')) }}
```

**Comment by kruiz122893** [comment]
Undefined property: LdapRecord\Models\Relations\HasMany::$map (View: /mnt/f/glutton/resources/views/employee/index.blade.php)

**Comment by stevebauman** [comment]
Whoops, my mistake, try:

```php
{{ dd(auth()->user()->groups()->get()->map->getFirstAttribute('cn')) }}
```

**Comment by kruiz122893** [comment]
No problem!!

![image](https://user-images.githubusercontent.com/26779953/82942525-51b3dd00-9f55-11ea-9fbb-de3705dfca0e.png)

**Comment by stevebauman** [comment]
Okay that looks correct, now try:

```blade
{{ dd(auth()->user()->groups()->recursive()->get()->map->getFirstAttribute('cn')) }}
```

**Comment by kruiz122893** [comment]
The same result:

![image](https://user-images.githubusercontent.com/26779953/82942638-7f992180-9f55-11ea-9473-deada251ffd8.png)

**Comment by kruiz122893** [comment]
This is the administrators group:


![image](https://user-images.githubusercontent.com/26779953/82942870-e74f6c80-9f55-11ea-90c1-93ac94d7ddf3.png)


![image](https://user-images.githubusercontent.com/26779953/82942906-f3d3c500-9f55-11ea-8a87-94f637dc3ca4.png)


The group isn't global maybe?

**Comment by stevebauman** [comment]
Have you can `composer update` yet? Also, try what I mentioned above and post your result:

```blade
{{ dd(auth()->user()->groups()->recursive()->get()->map->getFirstAttribute('cn')) }}
```

**Comment by kruiz122893** [comment]
Yes i did 

![image](https://user-images.githubusercontent.com/26779953/82945179-b8d39080-9f59-11ea-902d-c3366e5bc893.png)






![image](https://user-images.githubusercontent.com/26779953/82945205-c5f07f80-9f59-11ea-9ddd-340ba1052ff9.png)




Yes, yes  i did 


![image](https://user-images.githubusercontent.com/26779953/82945358-fdf7c280-9f59-11ea-9be1-837bfe658b83.png)

**Comment by kruiz122893** [comment]
The ldap base DN were set on Users for example: 



CN=Users,CN=administrator,CN=Users,DC=corp,DC=amavis,DC=com'),


I changed to:

CN=administrator,CN=Users,DC=corp,DC=amavis,DC=com'),



and now i have : 



![image](https://user-images.githubusercontent.com/26779953/82946394-82971080-9f5b-11ea-8493-c5583ec0b89d.png)





This was the solution:



![image](https://user-images.githubusercontent.com/26779953/82946573-d144aa80-9f5b-11ea-9b8c-474a33d6cdef.png)

**Comment by kruiz122893** [comment]
Thank you dude
 the ticket was result

**Comment by kruiz122893** [comment]
Hi @stevebauman i want to write these comment because this is a other way to solve this issue

Put in your Controller:

`        $memberofgroups = auth()->user()->groups()->get()->map->getFirstAttribute('cn');
`
and running into blade a   foreach:


```
   @foreach($memberofgroups as $memberofgroup)
          @if($memberofgroup == "glutton-admin")
            <a  class="btn btn-warning" href="{{ route('export') }}">Export User Data</a>
        @endif

      @endforeach

```


the currently trait it's not working =( and just do "composer update"
