### ISSUE TITLE
[Help] How to approach roleless user permissions

### ISSUE THREAD

**Issue by benjivm** [larapacks/authorization#26]
Hi there, thanks for the package, I am starting to implement this because of https://github.com/DirectoryTree/LdapRecord-Laravel/issues/174 (which has this workaround: https://github.com/spatie/laravel-permission/issues/1156).

I prefer the simplicity of this package over laravel-permission which is why I am not using the workaround, however I was wondering how to approach direct permissions without roles.

My application is built around permissions instead of roles, generally following [this idea](https://spatie.be/docs/laravel-permission/v4/best-practices/roles-vs-permissions), because my users need access to different parts of the application in ways that don't easily conform to role-based authorization (with a few exceptions, e.g. Admin/Manager roles that have large groups of permissions). Only a handful of users share the same permission scheme, therefore in order to primarily rely on roles I'd basically be treating them like permissions.

What I'd like is a way to do stuff like this:

```php
$user->givePermissionTo([
    'see salesforce quote notes',
    'see salesforce quote attachments',
]);

$user->revokePermissionTo('send sms');
```

Right now I am using a custom `HasPermissions` trait heavily borrowing from (https://github.com/spatie/laravel-permission/blob/main/src/Traits/HasPermissions.php):
```php
namespace App\Traits;

use Illuminate\Database\Eloquent\ModelNotFoundException;
use Larapacks\Authorization\Permission;

trait HasPermissions
{
    /**
     * Retrieve the given permission(s).
     *
     * @param $permissions
     *
     * @return mixed
     */
    public function getPermission($permissions)
    {
        if (is_numeric($permissions)) {
            return Permission::find($permissions);
        }

        if (is_string($permissions)) {
            return Permission::firstWhere('name', $permissions);
        }

        if (is_array($permissions)) {
            return Permission::whereIn('name', $permissions)->get();
        }

        return $permissions;
    }

    /**
     * Grant the given permission(s).
     *
     * @param ...$permissions
     *
     * @return $this
     */
    public function givePermissionTo(...$permissions)
    {
        $permissions = collect($permissions)
            ->flatten()
            ->map(function ($permission) {
                if (empty($permission)) {
                    return false;
                }

                return $this->getPermission($permission);
            })
            ->filter(function ($permission) {
                return $permission instanceof Permission;
            })
            ->map->id
            ->all();

        $model = $this->getModel();

        if ($model->exists) {
            $this->permissions()->sync($permissions, false);
            $model->load('permissions');
        } else {
            $class = \get_class($model);

            $class::saved(
                function ($object) use ($permissions, $model) {
                    if ($model->getKey() != $object->getKey()) {
                        return;
                    }

                    $model->permissions()->sync($permissions, false);
                    $model->load('permissions');
                }
            );
        }

        return $this;
    }

    /**
     * Revoke the given permission(s).
     *
     * @param $permission
     *
     * @return $this
     */
    public function revokePermissionTo($permission)
    {
        $this->permissions()->detach($this->getPermission($permission));
        $this->load('permissions');

        return $this;
    }

    /**
     * Check if the user has the given permission(s).
     *
     * @param $permission
     *
     * @return bool
     */
    public function hasPermissionTo($permission)
    {
        if (is_string($permission)) {
            $permission = Permission::firstWhere('name', $permission);
        }

        if (is_int($permission)) {
            $permission = Permission::find($permission);
        }

        if (! $permission instanceof Permission) {
            throw new ModelNotFoundException();
        }

        return $this->hasDirectPermission($permission) || $this->hasPermissionViaRole($permission);
    }

    /**
     * Determine if the user has the given permission via roles.
     *
     * @param Permission $permission
     *
     * @return bool
     */
    protected function hasPermissionViaRole(Permission $permission)
    {
        return $this->hasRole($permission->roles);
    }

    /**
     * Determine if the user has the given permission.
     *
     * @param $permission
     *
     * @return bool
     */
    public function hasDirectPermission($permission)
    {
        if (is_string($permission)) {
            $permission = Permission::firstWhere('name', $permission);
        }

        if (is_int($permission)) {
            $permission = Permission::find($permission);
        }

        if (! $permission instanceof Permission) {
            throw new ModelNotFoundException();
        }

        return $this->permissions->contains('id', $permission->id);
    }
}
```

Is there already a way to do this I'm missing? Do you have a recommendation for this approach?

**Comment by stevebauman** [comment]
Hi @benjivm!

>  What I'd like is a way to do stuff like this:

```php
$user->givePermissionTo([
    'see salesforce quote notes',
    'see salesforce quote attachments',
]);

$user->revokePermissionTo('send sms');
```

I just pushed an update to add this functionality to `User` models, instead of just on `Role` models. You can now do this:

```php
$user->grant([
    'see salesforce quote notes',
    'see salesforce quote attachments',
]);

$user->revoke('send sms');
```

Using `$user->hasPermission()` will first check if the user has been given the explicit permission, then check if they have a role that contains that permission. This works for `$user->hasPermissions()` and `$user->hasAnyPermissions()`. 

Before I create a new release, does this new functionality suffice for everything your application needs for addressing your concerns you mentioned above? If not, can you let me know what further adjustments may help you?

**Comment by benjivm** [comment]
@stevebauman that sounds great, thank you for your work! I can think of one more: `syncPermissions(['one, two'])` (sync with detaching).

And for clarification, will your update actually be used like this?
```php
$user->permissions()->grant([
    'see salesforce quote notes',
    'see salesforce quote attachments',
]);

$user->permissions()->revoke('send sms');
```

I think `grant()` and `revoke()` alone as the model trait without a `permission` keyword is too ambiguous.

**Comment by stevebauman** [comment]
> I can think of one more: syncPermissions(['one, two']) (sync with detaching).

Okay great let me see if I can implement this 👍 

> And for clarification, will your update actually be used like this?
```php
$user->permissions()->grant([
    'see salesforce quote notes',
    'see salesforce quote attachments',
]);

$user->permissions()->revoke('send sms');
```

No, you can call `grant()` or `revoke()` methods on your `User` or `Role` model, as they only pertain to permissions.

> I think grant() and revoke() alone as the model trait without a permission keyword is too ambiguous.

If I adjust the names then it will be a major breaking change, since the included `Role` model utilizes these names.

You can always adjust them yourself though directly on your `User` model:

```php
class User extends Model
{
    use Authorizable {
        grant as grantPermission;
        revoke as revokePermission;
    }

    // ...
}
```

**Comment by stevebauman** [comment]
Also, FYI I've started the migration of this package to the [DirectoryTree](https://github.com/DirectoryTree/Authorization) organization, so I have a single umbrella of packages to maintain.

I'll be sunsetting the "Larapacks" organization -- but of course I won't be deleting any repositories or removing anything from packagist, so developers have time to swap the `Larapacks` namespace in their code to `DirectoryTree`.

**Comment by benjivm** [comment]
@stevebauman thanks!

**Comment by stevebauman** [comment]
Okay, I've just pushed this update on the [DirectoryTree\Authorization](https://github.com/DirectoryTree/Authorization) repository. You can now sync permissions via the `grantOnly()` method:

```php
$user->grant(['users.create', 'users.edit']);

// "users.edit" will be removed:
$user->grantOnly(['users.create']);
```

I didn't want pollute user models with a `syncPermissions` method, as it's a bit out of the scope of the API (i.e. doesn't conform with `revoke()` and `revokeAll()`).

Though you may always rename it as shown above like so:

```php
class User extends Model
{
    use Authorizable {
        grant as grantPermission;
        grantOnly as syncPermissions;
        revoke as revokePermission;
        revokeAll as revokeAllPermissions;
    }

    // ...
}
```

I'll be creating a new release on the DirectoryTree repository tomorrow morning, with migration steps on this repository for other developers who were using it as well 👍 

I hope this helps!

**Comment by benjivm** [comment]
It _absolutely_ does, great stuff 👍
